# Generated by Django 4.2.1 on 2023-10-28 12:05

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(default=1, help_text='Estimate approximate production time in minutes (min 1).', validators=[django.core.validators.MinValueValidator(1, 'Production time should be more than 1 min.')], verbose_name='Recipe production time'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Could not be empty. Must be unique.', image_field=None, max_length=50, samples=None, unique=True, verbose_name='Tag color HEX code.'),
        ),
    ]
