# Generated by Django 4.2.1 on 2023-09-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_ingredient_unique_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='about',
            new_name='text',
        ),
    ]
