# Generated by Django 4.2.1 on 2023-10-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_about_recipe_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='production_time',
            new_name='cooking_time',
        ),
    ]
