# Generated by Django 4.2.1 on 2023-10-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_production_time_recipe_cooking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_tag',
            name='author',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.TextField(help_text='Show the final result.', verbose_name='Recipe image'),
        ),
    ]
