# Generated by Django 4.2.1 on 2023-10-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Show the final result.', upload_to='recipes/image', verbose_name='Recipe image'),
        ),
    ]
