# Generated by Django 4.2.1 on 2023-10-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Add all components to your dish.', related_name='recipes', through='recipes.Ingredient_Recipe', to='recipes.ingredient', verbose_name='Recipe ingregiemts'),
        ),
    ]
