name: Main Foodgram workflow

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: PEP8 check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install isort
      - name: Test with isort and flake8
        run: |
          python -m isort .
          python -m flake8

